version: '3.9'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '23910:5432'